trigger:
- master

pool:
  default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'

- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub'  # Mettez à jour avec le nom de votre connexion Docker Hub
    repository: 'olfasalem/ramadan'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
